apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: kubeivan/vprofiledb
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
           claimName: db-pv-claim  
      
      initContainers:
<<<<<<< HEAD
      - name: busybox
        image: busybox
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
=======
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
>>>>>>> ca3f7885ade17ff91ad2e805bfb0f51147282a50
